config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :places
  resources :users
  resources :videos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :videos, dependent: :destroy
  has_one_attached :place_image
  
  def get_image
    if place_image.attached?
      place_image
    else
      'no_image.jpg'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :videos, dependent: :destroy
  
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  
  
  
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
  belongs_to :place
  has_one_attached :movie
  
  default_scope -> { order(created_at: :desc) }
  
  validates :user_id, presence: true
  validates :content, presence: true
  
  def get_movie
    if movie.attached?
      movie
    else
      'no_image.jpg'
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  
  private

    # ユーザーのログインを確認する
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  
  def index
    @places = [
      { id: 1, name: "東京ドーム", image: 'parks/tokyo_dome.jpg'},
      { id: 2, name: "エスコンフィールド", image: 'parks/esconfield.jpg'},
      { id: 3, name: "楽天モバイルパーク", image: 'parks/rakuten_mobile_park.jpg'},
      { id: 4, name: "メットライフドーム", image: 'parks/mettolife_dome.jpg'},
      { id: 5, name: "zozoマリンスタジアム", image: 'parks/zozomarine.jpg'},
      { id: 6, name: "明治神宮球場", image: 'parks/jingu.jpg'},
      { id: 7, name: "横浜スタジアム", image: 'parks/yokohama.jpg'},
      { id: 8, name: "バンテリンドーム", image: 'parks/banterin.jpg'},
      { id: 9, name: "京セラドーム", image: 'parks/kyosera.jpg'},
      { id: 10, name: "阪神甲子園球場", image: 'parks/kohshien.jpg'},
      { id: 11, name: "マツダスタジアム", image: 'parks/mazda.jpg'},
      { id: 12, name: "paypayドーム", image: 'parks/paypay_dome.jpg'}
    ]
  end
  
  def new
    @place = Place.new
  end
  
  def create
    @place = Place.new(place_params)
    if @place.save
      flash[:success] = "球場が登録されました"
      redirect_to places_path
    else
      render new_place_path
    end
  end
  
  def show
    @place = Place.find(params[:id])
    @videos = @place.videos.all
  end
  
  private
  
  def place_params
    params.require(:place).permit(:place, :place_image)
  end
  
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      forwarding_url = session[:forwarding_url]
      reset_session
      log_in user
      redirect_to user
    else
      flash.now[:danger] = "メールアドレスかパスワードが間違っています"
      render 'new', status: :unprocessable_entity
    end
  end
  
  def destroy
    log_out
    redirect_to root_url, status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    @videos = @user.videos.paginate(page: params[:page])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in @user
      flash[:success] = "新規登録完了"
      redirect_to @user
    else
      render 'new', status: :unprocessable_entity
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "プロフィールを変更しました"
      redirect_to @user
    else
      render 'edit', status: :unprocessable_entity
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "ユーザーを削除しました"
    redirect_to root_path, status: :see_other
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :introduction)
    end
    
    
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url, status: :see_other) unless corrent_user?(@user)
    end
    
    def admin_user
      redirect_to(root_url, status: :see_other) unless current_user.admin?
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :destroy]
  
  def index
    @videos = Video.all
  end
  
  def new
    @video = Video.new
  end

  def show
    @video = Video.find(params[:id])
  end

  def create
    @video = current_user.videos.build(video_params)
    @video.movie.attach(params[:content])
    if @video.save
      flash[:success] = "投稿完了"
      redirect_to user_path(current_user), status: :see_other
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    flash[:success] = "投稿が削除されました"
    if request.referrer.nil?
      redirect_to root_url, status: :see_other
    else
      redirect_to request.referrer, status: :see_other
    end
  end
  
  private

    def video_params
      params.require(:video).permit(:content, :movie, :place_id)  #place_id追加
    end
    
    def correct_user
      @video = current_user.videos.find_by(id: params[:id])
      redirect_to(root_url, status: :see_other) if @video.nil?
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end
  
  def store_location
    session[:forwarding_url] = request.original_url uf request.get?
  end
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  
  def current_user?(user)
    user && user == current_user
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  
  def gravatar_for(user, options = { size: 80 })
    size = options[:size]
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ballpark</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header ckass="navbar fixed-top navbar-light gb-light navbar-expand-lg">
      <div class="container">
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <div class='btn-toolbar' role="toolbar">
              <% if logged_in? %>
                <li>
                  <%= link_to logout_path, data: { "turbo-method": :delete } do %>
                    <button type="button" class="btn btn-primary">ログアウト</button>
                  <% end %>
                </li>
                
                <li>
                  <%= link_to new_video_path do %>
                    <button type="button" class="btn btn-success">投稿</button>
                  <% end %>
                </li>
                <li>
                  <%= link_to places_path do %>
                    <button type="button" class="btn btn-success">球場</button>
                  <% end %>
                </li>
              <% end%>
            </div>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container my-5">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/places/index.html.erb
<div class="d-flex justify-content-start">
  <h1 class="mb-4">球場</h1>
</div>

<table class="table">
  <% @places.each_slice(3) do |place_group| %>
    <tr>
      <% place_group.each do |p| %>
        <td>
          <%= image_tag(asset_path(p[:image]), size: "300x200") %>
          <%= link_to p do %>
            <p><%= p[:name] %></p>
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/places/new.html.erb
<div class="new_place">
  <h1>球場登録</h1>
  <div class="row">
    <div class="col-md-6 offset-md-3">
  
      <%= form_with model: @place do |f| %>
      
          <%= f.label :place, "球場名" %>
          <%= f.text_field :place %>
          
          <%= f.label :place_image, "球場画像" %>
          <%= f.file_field :place_image %>
    
          
          <%= f.submit "球場登録", class: "btn btn-primary" %>
      <% end %>
     
    </div>
  </div>
  
</div>

app/views/places/show.html.erb
<h1>Video</h1>

app/views/shared/_error_message.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <<%= "#{object.errors.count}つのエラーがあります。" %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_video_form.html.erb
<%= form_with(model: @video) do |f| %>
  <%= render 'shared/error_message', object: f.object %>
  
  <div class="movie">
    <%= f.file_field :movie %>
  </div>
  
  <div class="field">
    <%= f.text_area :content, placeholder: "本文" %>
  </div>
  
  <!--<div class="place">-->
  <!--  <%= %>-->
  <!--</div>-->
  
  <%= f.submit "投稿する", class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<h1>プロフィール編集</h1>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <%= form_with(model: @user) do |f| %>
      <%= render 'shared/error_message', object: f.object %>
      
      <%= f.label :name, "名前" %>
      <%= f.text_field :name %>
      
      <%= f.label :introduction, "自己紹介文" %>
      <%= f.text_area :introduction %>

      <%= f.submit "保存する", class: "btn btn-primary" %>
    <% end %>
    
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>すべてのユーザー</h1>
<ul class="users d-flex justify-content-around flex-wrap pt-3">
  <% @users.each do |user| %>
  <li class="shadow mb-3 w-30 center">
    <%= link_to user do%>
      <%= gravatar_for user, size: 50 %>
      <h3><%= user.name %></h3>
    <% end %>
  </li>
  <% end %>
</ul>

<%= will_paginate @users, previous_label: '< 前へ', next_label: '次へ >' %>

app/views/users/new.html.erb
<div class="signup">
  <h1>新規登録</h1>
  <div class="row">
    <div class="col-md-6 offset-md-3">
  
      <%= form_with model: @user do |f| %>
      <%= render 'shared/error_message', object: f.object %>
          <%= f.label :name, "名前" %>
          <%= f.text_field :name %>
          
          <%= f.label :email, "メールアドレス" %>
          <%= f.email_field :email %>
    
          <%= f.label :password, "パスワード" %>
          <%= f.password_field :password %>
    
          <%= f.label :password_confirmation, "パスワード確認" %>
          <%= f.password_field :password_confirmation %>
          
          <%= f.submit "新規登録", class: "btn btn-primary" %>
      <% end %>
     
    </div>
  </div>
  
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-4">
      <%= gravatar_for @user %>
    </div>
    <div class="col-8">
      <h1><%= @user.name %></h1>
      <p><%= @user.introduction%></p>
    </div>
  </div>
</div>

<% if current_user.admin? && !current_user?(user) %>
  <%= link_to "削除する", root_path, data: { "turbo-method": :delete,
                                          turbo_confirm: "本当に削除しますか？" } %>
<% end %>


  <div class="row pt-3">
    <div class="col-md-8 offset-md-2">
      <% if @videos.any? %>
        <h3>投稿数 (<%= @user.videos.count %>)</h3>
        <ol class="videos">
          <%= render "videos/index" %>
        </ol>
        <%= will_paginate @videos, previous_label: '< 前へ', next_label: '次へ >' %>
      <% end %>
    </div>
  </div>

    

app/views/videos/_index.html.erb
<div class="videos">
  <% @videos.each do |video| %>
    <%= video_tag(video.get_movie) %>
    <%= video.content %>
    
  <% end %>
</div>

app/views/videos/_videos.html.erb
<li class="bg-light p-3 mb-2" id="video-<%= videoid %>">
  <%= link_to gravatar_for(video.user, size: 50), video.user %>
  <span class="user"><%= link_to video.user.name, video.user %></span>
  <span class="timestamp float-end">
    <%= time_ago_in_words(video.created_at) %>
  </span>
  <%= link_to video do%>
    <h3><%= video.content %></h3>
  <% end %>
  
  <% if video.video.attached? %>
    <%= image_tag video.movie, class:"post-movie" %>
  <% end %>
  
  <% if current_user?(video.user) %>
    <div class="text-end">
      <%= link_to "削除", video, data: { "turbo-method": :delete,
                                            turbo_confirm: "本当に削除しますか？" }, class:"text-danger" %>
    </div>
  <% end %>
</li>

app/views/videos/new.html.erb
<% provide(:title, '動画投稿') %>
<h1>投稿作成</h1>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <%= render 'shared/video_form' %>
  </div>
</div>